src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Scheb\TwoFactorBundle\Model\Google\TwoFactorInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User extends BaseUser implements TwoFactorInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DriverToken", mappedBy="user", orphanRemoval=true)
     */
    private $driverTokens;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(name="googleAuthenticatorSecret", type="string", nullable=true)
     */
    private $googleAuthenticatorSecret;

    public function __construct()
    {
        parent::__construct();

        $this->driverTokens = new ArrayCollection();
    }

    /**
     * @return Collection|DriverToken[]
     */
    public function getDriverTokens(): Collection
    {
        return $this->driverTokens;
    }

    /**
     * @param DriverToken $driverToken
     * @return User
     */
    public function addDriverToken(DriverToken $driverToken): self
    {
        if (!$this->driverTokens->contains($driverToken)) {
            $this->driverTokens[] = $driverToken;
            $driverToken->setUser($this);
        }

        return $this;
    }

    /**
     * @param DriverToken $driverToken
     * @return User
     */
    public function removeDriverToken(DriverToken $driverToken): self
    {
        if ($this->driverTokens->contains($driverToken)) {
            $this->driverTokens->removeElement($driverToken);
            // set the owning side to null (unless already changed)
            if ($driverToken->getUser() === $this) {
                $driverToken->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeInterface $createdAt
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return bool
     */
    public function isGoogleAuthenticatorEnabled(): bool
    {
        return $this->googleAuthenticatorSecret ? true : false;
    }

    /**
     * @return string
     */
    public function getGoogleAuthenticatorUsername(): string
    {
        return $this->username;
    }

    /**
     * @return string
     */
    public function getGoogleAuthenticatorSecret(): string
    {
        return $this->googleAuthenticatorSecret;
    }

    /**
     * @param null|string $googleAuthenticatorSecret
     */
    public function setGoogleAuthenticatorSecret(?string $googleAuthenticatorSecret): void
    {
        $this->googleAuthenticatorSecret = $googleAuthenticatorSecret;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\DriverToken;
use App\Entity\User;
use App\Form\Type\ConfirmTfaTokenType;
use App\Form\Type\ConfirmPasswordType;
use App\Model\ConfirmTfaToken;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ProfileController extends Controller
{
    /**
     * @param Request $request
     * @return Response
     */
    public function securityAction(Request $request)
    {
        $tfaForm = $this->createForm(ConfirmPasswordType::class, null, ['action' => $this->generateUrl('profile_generate_tfa')]);

        return $this->render(
            'profile/security.html.twig',
            [
                'tfaForm' => $tfaForm->createView()
            ]
        );
    }

    public function generateTfaAction(Request $request)
    {
        $googleAuth = $this->get('scheb_two_factor.security.google_authenticator');

        $tfaForm = $this->createForm(ConfirmPasswordType::class);
        $tfaForm->handleRequest($request);

        $confirmToken = new ConfirmTfaToken($this->getUser()->getUsername(), $googleAuth->generateSecret());
        $confirmTokenForm = $this->createForm(ConfirmTfaTokenType::class, $confirmToken);
        $confirmTokenForm->handleRequest($request);

        if ($confirmTokenForm->isSubmitted() || ($tfaForm->isSubmitted() && $tfaForm->isValid())) {
            if ($confirmTokenForm->isSubmitted() && $confirmTokenForm->isValid()) {
                /** @var User $user */
                $user = $this->getUser();
                $user->setGoogleAuthenticatorSecret($confirmToken->getGoogleAuthenticatorSecret());

                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('profile_security');
            }

            return $this->render(
                'profile/security.html.twig',
                [
                    'confirmToken' => $confirmToken,
                    'secretQrToken' => $googleAuth->getQRContent($confirmToken),
                    'confirmTokenForm' => $confirmTokenForm->createView(),
                    'focusConfirmTfaTokenModal' => true,
                ]
            );
        }

        if (!$tfaForm->isSubmitted()) {
            return $this->redirectToRoute('profile_security');
        }

        return $this->render(
            'profile/security.html.twig',
            [
                'tfaForm' => $tfaForm->createView(),
                'focusEnableTfaForm' => true,
            ]
        );
    }

    /**
     * @param Request $request
     * @return Response
     */
    public function driverTokenAction(Request $request)
    {
        $form = $this->createForm(FormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newDriverToken = new DriverToken();
            $newDriverToken->setUser($this->getUser());

            $em = $this->getDoctrine()->getManager();
            $em->persist($newDriverToken);
            $em->flush();

            return $this->redirectToRoute('profile_driver_token');
        }

        $currentDriverToken = $this->getDoctrine()->getRepository('App:DriverToken')->findActiveDriverTokenByUser($this->getUser());

        return $this->render(
            'profile/driverToken.html.twig',
            [
                'form' => $form->createView(),
                'driverToken' => $currentDriverToken
            ]
        );
    }
}

templates/profile/driverToken.html.twig
{% extends 'profile/layout.html.twig' %}

{% block title %}Driver Token{% endblock %}

{% block profile_content %}
    {{ form_start(form) }}
        <div class="form-group">
            <label for="profile_driver_token" class="form-control-label">Your Driver Token</label>
            <div class="form-control d-flex align-items-center pt-2 pb-2">
                <span id="profile_driver_token" class="mr-auto">
                    {{ driverToken.token }}
                </span>
                <button type="submit" class="btn btn-sm btn-primary ml-2">
                    <i class="fa fa-sync-alt"></i> Regenerate
                </button>
            </div>
            <small class="text-muted">
                This is your unique token to use with the tracking application. Keep this safe.
            </small>
        </div>

        {{ form_rest(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/profile/layout.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col col-md-3">
            <div class="list-group">
                <a href="{{ path('fos_user_profile_show') }}" class="list-group-item list-group-item-action{{ app.request.get('_route') in ['fos_user_profile_show', 'fos_user_profile_edit'] ? ' active' }}">
                    <i class="fas fa-fw fa-user mr-1"></i> Profile
                </a>
                <a href="{{ path('profile_security') }}" class="list-group-item list-group-item-action{{ app.request.get('_route') in ['profile_security', 'fos_user_change_password'] ? ' active' }}">
                    <i class="fas fa-fw fa-lock mr-1"></i> Security
                </a>
                <a href="{{ path('profile_driver_token') }}" class="list-group-item list-group-item-action{{ app.request.get('_route') in ['profile_driver_token'] ? ' active' }}">
                    <i class="fas fa-fw fa-key mr-1"></i> Driver Token
                </a>
            </div>
        </div>
        <div class="col">
            <h1>
                {% block title %}{% endblock %}
            </h1>

            <hr>
            <div class="card">
                <div class="card-body">
            {% block fos_user_content %}{% endblock %}
            {% block profile_content %}{% endblock %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/profile/security.html.twig
{% extends 'profile/layout.html.twig' %}

{% block title %}Security{% endblock %}

{% block profile_content %}
    <div class="form-group">
        <label for="profile_tfa" class="form-control-label">Two Factor Authentication <span class="badge badge-{{ app.user.googleAuthenticatorEnabled ? 'success' : 'danger' }}">{{ app.user.googleAuthenticatorEnabled ? 'Enabled' : 'Disabled' }}</span></label>
        <div id="profile_tfa">
            {% if app.user.googleAuthenticatorEnabled %}
                <button data-toggle="modal" data-target="#enableTfaModal" class="btn btn-outline-secondary">Regenerate</button>
                <button data-toggle="modal" data-target="#disableTfaModal" class="btn btn-danger">Disable</button>
            {% else %}
                <button data-toggle="modal" data-target="#enableTfaModal" class="btn btn-success">Enable</button>
            {% endif %}
        </div>
    </div>

    <div>
        <a href="{{ path('fos_user_change_password') }}" class="btn btn-secondary">Change Password</a>
    </div>
{% endblock %}

{% block modals %}
    {% if tfaForm|default %}
    <div class="modal fade modal_auto-focus" id="enableTfaModal" tabindex="-1" role="dialog" aria-labelledby="enableTfaModal__title" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                {{ form_start(tfaForm) }}
                    <div class="modal-header">
                        <h5 class="modal-title" id="enableTfaModal__title">
                            Enable TFA
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ form_widget(tfaForm) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Enable TFA</button>
                    </div>
                    {{ form_rest(tfaForm) }}
                {{ form_end(tfaForm) }}
            </div>
        </div>
    </div>
    <div class="modal fade modal_auto-focus" id="generateTfaModal" tabindex="-1" role="dialog" aria-labelledby="generateTfaModal__title" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                {{ form_start(tfaForm) }}
                    <div class="modal-header">
                        <h5 class="modal-title" id="generateTfaModal__title">
                            Generate TFA
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ form_widget(tfaForm) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Generate TFA</button>
                    </div>
                    {{ form_rest(tfaForm) }}
                {{ form_end(tfaForm) }}
            </div>
        </div>
    </div>
    {% endif %}

    {% if confirmTokenForm|default %}
    <div class="modal fade modal_auto-focus" id="confirmTfaTokenModal" tabindex="-1" role="dialog" aria-labelledby="confirmTfaTokenModal__title" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                {{ form_start(confirmTokenForm) }}
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmTfaTokenModal__title">
                            {{ app.user.googleAuthenticatorEnabled ? 'Generate' : 'Enable' }} TFA
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>
                            Scan QR code:
                        </p>
                        <canvas id="tfa_qr"></canvas>
                        <p>
                            Or, enter the code manually:
                        </p>
                        <pre class="bg-light p-3"><code>{{ confirmToken.secret }}</code></pre>
                        {{ form_widget(confirmTokenForm) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">{{ app.user.googleAuthenticatorEnabled ? 'Generate' : 'Enable' }} TFA</button>
                    </div>
                    {{ form_rest(confirmTokenForm) }}
                {{ form_end(confirmTokenForm) }}
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qrious/4.0.2/qrious.min.js"></script>

    <script type="text/javascript">
        {% if secretQrToken|default %}
        (function() {
          new QRious({
            element: document.getElementById('tfa_qr'),
            value: {{ secretQrToken|json_encode|raw }},
            level: 'M',
            size: 180
          });
        })();
        {% endif %}

        $('.modal_auto-focus').on('shown.bs.modal', function () {
            $('input', this).first().trigger('focus')
        });

        $(window).on('load',function(){
            {% if focusEnableTfaForm|default %}
                $('#enableTfaModal').modal('show');
            {% endif %}
            {% if focusConfirmTfaTokenModal|default %}
                $('#confirmTfaTokenModal').modal('show');
            {% endif %}
        });
    </script>
{% endblock %}